Shop/Shop/ViewModels/CamerasListViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class CamerasListViewModel
    {
        public IEnumerable<Camera> allCameras { get; set; }

        public string currCategory { get; set; }
    }
}

Shop/Shop/ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Camera> favCameras { get; set; }
        public IEnumerable<Camera> available { get; set; }
    }
}

Shop/Shop/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Shop/Shop/Controllers/CamerasController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Shop.Controllers
{
    public class CamerasController : Controller
    {
        private readonly IAllCameras _allCameras;
        private readonly ICamerasCategory _allCategories;
        public CamerasController(IAllCameras iAllCameras, ICamerasCategory iCamerasCategory)
        {
            _allCameras = iAllCameras;
            _allCategories = iCamerasCategory;
        }
        [Route("Cameras/List")]
        [Route("Cameras/List/{Category}")]
        
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Camera> cameras = null;
            string currCategory = "";
            if(string.IsNullOrEmpty(category))
            {
                cameras = _allCameras.Cameras.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("IP", category, StringComparison.OrdinalIgnoreCase))
                {
                    cameras = _allCameras.Cameras.Where(i => i.Category.categoryName.Equals("IP")).OrderBy(i => i.id).Where(i=>i.available == true);
                }
                else if (string.Equals("WIFI", category, StringComparison.OrdinalIgnoreCase))
                { 
                
                    cameras = _allCameras.Cameras.Where(i => i.Category.categoryName.Equals("WIFI")).OrderBy(i => i.id).Where(i => i.available == true);
                }
                else if (string.Equals("VideoRecorder", category, StringComparison.OrdinalIgnoreCase))
                {

                    cameras = _allCameras.Cameras.Where(i => i.Category.categoryName.Equals("VideoRecorder")).OrderBy(i => i.id).Where(i => i.available == true);
                }
                else if (string.Equals("Cable", category, StringComparison.OrdinalIgnoreCase))
                {

                    cameras = _allCameras.Cameras.Where(i => i.Category.categoryName.Equals("Cable")).OrderBy(i => i.id).Where(i => i.available == true);
                }

                currCategory = _category;
                

            }
            
            var cameraobj = new CamerasListViewModel
            {

                allCameras = cameras,
                currCategory = currCategory
            };
            ViewBag.Title = "Страница с камерами";
           
            
            return View(cameraobj);
        }

    }
}

Shop/Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCameras _cameraRep;
       
        public HomeController(IAllCameras cameraRep)
        {
            _cameraRep = cameraRep;
            
        }
        public ViewResult Index()
        {
            var homeCameras = new HomeViewModel
            {
                favCameras = _cameraRep.getFavCameras
            };
            return View(homeCameras);
        }
    }
}

Shop/Shop/Controllers/MountingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class MountingController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

Shop/Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;
        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();
            if(shopCart.listShopItems.Count==0)
            {
                ModelState.AddModelError("", "У вас должны быть товары");
            }
            if(ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

Shop/Shop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;


namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCameras _cameraRep;
        private ShopCart _shopCart;
        private HomeController _homeController;
        public ShopCartController(IAllCameras cameraRep, ShopCart shopCart)

        {
            _cameraRep = cameraRep;
            _shopCart = shopCart;
            
        }
        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel { shopCart = _shopCart };
            return View(obj);
        }
        public RedirectToActionResult addToCart(int id)
        {
            var item = _cameraRep.Cameras.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult changesAvailbleRemove(int id)
        {
            _shopCart.ChangesAvailbleRemove(id);
            return RedirectToAction("Index");
        }
        public RedirectToActionResult changesAvailbleAdd(int id)
        {
            _shopCart.ChangesAvailbleAdd(id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public RedirectToActionResult changesAvailbleSearh(string str)
        {
            _shopCart.ChangesAvailbleSearch(str);
            return RedirectToAction("Index", "Home");
        }
        
        public RedirectToActionResult removeFromCart(string id)
        {
            _shopCart.RemoveFromCart(id);
            return RedirectToAction("Home/Index");
        }
    }
}

Shop/Shop/Views/Cameras/List.cshtml
<h3>@Model.currCategory</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Camera camera in Model.allCameras)
        {
       @Html.Partial("AllCameras", camera )
        }
    }
</div>

      

Shop/Shop/Views/Home/Index.cshtml
@model HomeViewModel
<h1>Поиск</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Camera camera in Model.favCameras)
        {
            @Html.Partial("AllCameras", camera)
        }
    }
</div>

Shop/Shop/Views/Mounting/Index.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <title>Editable Content</title>
</head>
<dody><div id="edit" contenteditable="true"></div>
    <script>
        var edit = document.getElementById('edit');
        edit.innerHTML = localStorage.getItem('edit');
        edit.addEventListener('blur', function () {
            localStorage.setItem('edit', this.innerHTML);
        })
    </script>
</dody>
</html>

Shop/Shop/Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-5">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="adress"></label>
            <div class="col-md-5">
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершить заказ"/>
    </form>
</div>

Shop/Shop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Shop/Shop/Views/Shared/AllCameras.cshtml
@model Camera
<div class=" col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Добавить в корзину</a></p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="changesAvailbleRemove" asp-route-id="@Model.id">Удалить</a></p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="changesAvailbleAdd" asp-route-id="@Model.id">Вернуть</a></p>
</div>

Shop/Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel=" stylesheet" type="text/css" />
    <link href="~/css/style.css" rel=" stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/Cameras/List">Все товары</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cameras/List/IP">IP камеры</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cameras/List/WIFI">Wi-Fi камеры</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cameras/List/VideoRecorder">Видео регистраторы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cameras/List/Cable">Кабели</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Mounting/">Монтаж</a>
                        </li>
                    </ul>
                    <form method="post" asp-controller="ShopCart" asp-action="changesAvailbleSearh">
                        <label>Поиск:</label><br />
                        <input type="text" name="str" />
                        <input type="submit" value="Найти" />
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2021, Inc.</p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Shop/Shop/Views/ShopCart/Index.cshtml
@using Shop.Data.Models
@model ShopCartViewModel
<div class="container mt-5">
    @foreach (var el in Model.shopCart.listShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Камера:</b>@el.camera.name<br />
            <b>Цена:</b>@el.camera.price.ToString("c")
            <a class="btn btn-warning" asp-controller="ShopCart" asp-action="removeFromCart" asp-route-id="@Model.shopCart.ShopCartId">Удалить</a>
        </div>
    }
    <hr />
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>